[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false

[[plugins]]
  package = "/plugins/throw-an-error"

[[plugins]]
  package = "/plugins/do-something-on-error"